name: Test Action install-win-store-python

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-install-win-store-python:
    name: Test Win Store Python
    runs-on: windows-latest
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: [ "3.8", "3.9", "3.10", "3.11" ]
    steps:
    - uses: actions/checkout@v3
    - name: Install Windows Store Python
      uses: ./.github/actions/install-win-store-python
      with:
        python-version: ${{ matrix.python-version }}
    - name: Test Windows Store Python Install
      run: |
        $PythonExeSubDir = "\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.${{ matrix.python-version }}_qbz5n2kfra8p0\python.exe"
        $ExpectedPythonPath = Join-Path "$env:LOCALAPPDATA" "$PythonExeSubDir"
        if ( "$((Get-Command python).Path)" -ne "$ExpectedPythonPath" ) {
          echo "Python is at $((Get-Command python).Path)"
          echo "Python was expected at $ExpectedPythonPath"
          exit 1
        }
        if ( "$(python -V)" -cnotlike "Python ${{ matrix.python-version }}*" ) {
          echo "Found $(python -V)"
          echo "Expected Python ${{ matrix.python-version }}"
          exit 1
        }
